apiVersion: v1
kind: Secret
metadata:
  name: django-deploy-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGhpc2lzYXRlc3R0aW5nLg==
  MYSQL_DB: R2lmdGNhcmRTaXRlREI=
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==
  ALLOWED_HOSTS: "Kio="  # base64-encoded value for "*,"
